import { esc, layout, SITE_ORIGIN } from './render.ts';
import type { IndexBundle } from '../types/bundles.ts';
import type { MetaRecord } from '../types/meta.ts';

/**
 * The page that says what all of this found.
 *
 * Everything else here is a table. A table is the right shape for a reading and
 * the wrong shape for a claim, and this project had spent months measuring
 * things nobody else publishes without ever once stating one of them in a
 * sentence. Somebody arriving at a grid of four hundred repository names has to
 * do the work of noticing themselves, and almost nobody does.
 *
 * Every sentence here is assembled from the bundle with its figures
 * interpolated, never written by hand and never written by a model. That is the
 * only construction that cannot go stale: the numbers move daily, and a hand-
 * written sentence about them is wrong within a week of being true. A finding
 * whose figures fall below the bar it needs simply does not render.
 *
 * Each one carries the same three things: what was measured, the sample it
 * rests on, and a link to the page holding the evidence. A claim without all
 * three is an opinion with a number attached.
 */

export interface Finding {
  /** Short enough to be a headline, with the figure in it. */
  headline: string;
  /** What was measured and against what. One sentence, no hedging. */
  detail: string;
  /** The sample. Never optional — a figure without one is not a reading. */
  basis: string;
  href: string;
  /** Why nobody else has this. Empty where the answer is "they might". */
  novelty: string;
}

function plural(count: number, one: string, many: string): string {
  return count === 1 ? one : many;
}

/**
 * Every finding the current readings support, strongest first.
 *
 * Ordered by how surprising the figure is rather than by which collector
 * produced it, because a reader does not care which of twenty jobs found a
 * thing. Anything without enough behind it is dropped rather than softened.
 */
export function findingsFrom(index: IndexBundle): Finding[] {
  const found: Finding[] = [];
  const { contributors, staleness, names, advisories, questions, hiring, incidents, images, lifecycle } =
    index;

  if (contributors.measured > 0 && contributors.singleAuthor > 0) {
    const worst = contributors.concentrated[0];
    found.push({
      headline: `${contributors.singleAuthor} of ${contributors.measured} widely used projects rest half their history on one person`,
      detail:
        worst === undefined
          ? 'Counting from the most prolific contributor down, a single person accounts for half of all commits.'
          : `Counting from the most prolific contributor down, one person accounts for half of all commits. The most concentrated is ${worst.repo}, where the largest single contributor wrote ${worst.topShare.toFixed(0)}% of ${worst.commits.toLocaleString('en')} commits.`,
      basis: `Contributor histories of ${contributors.measured} repositories, read weekly from GitHub. Commit count is not contribution, and this is history rather than the present.`,
      href: '/ecosystem',
      novelty: 'Every health signal in circulation measures activity. None measures who is producing it.',
    });
  }

  if (staleness.overAYear > 0 && staleness.measured > 0) {
    const quietest = staleness.quietest[0];
    found.push({
      headline: `${staleness.overAYear} of ${staleness.measured} tracked packages have not shipped a release in over a year`,
      detail:
        quietest === undefined
          ? 'Read from the registries themselves rather than from a repository’s last push.'
          : `Read from the registries rather than from a repository’s last push — a push is what a maintainer does for themselves, a release is what reaches the projects depending on them. The longest silence is ${quietest.name} on ${quietest.registry}, ${quietest.days.toLocaleString('en')} days.`,
      basis: `${staleness.measured} packages across npm, PyPI and crates.io, read daily. Median time since release across all of them is ${staleness.medianDays ?? 0} days.`,
      href: '/ecosystem',
      novelty: 'Every "is this maintained" badge reads the wrong field.',
    });
  }

  if (names.found > 0) {
    const first = names.byPackage[0];
    found.push({
      headline: `${names.found} package ${plural(names.found, 'name', 'names')} one keystroke from something you install already exist on npm`,
      detail:
        first === undefined
          ? 'Generated by deleting or transposing one character, then asked of the registry.'
          : `Generated by deleting or transposing one character in a real package name, then asked of the registry directly. ${first.canonical} alone has ${first.neighbours.length}: ${first.neighbours.slice(0, 4).map((n) => n.name).join(', ')}.`,
      basis: `${names.swept} of the most installed packages swept. Deletions and transpositions only, so this finds fewer than exist. Existence is the entire claim — none of these is called malicious.`,
      href: '/ecosystem',
      novelty: 'npm’s own search ranks by popularity, which is exactly the ordering that hides these.',
    });
  }

  const worstEcosystem = advisories.byRegistry[0];
  const bestEcosystem = advisories.byRegistry[advisories.byRegistry.length - 1];
  if (
    worstEcosystem !== undefined &&
    bestEcosystem !== undefined &&
    worstEcosystem !== bestEcosystem &&
    worstEcosystem.perAffected !== null &&
    bestEcosystem.perAffected !== null
  ) {
    found.push({
      headline: `A ${worstEcosystem.registry} package carries ${(worstEcosystem.perAffected / bestEcosystem.perAffected).toFixed(1)}× the advisory load of a ${bestEcosystem.registry} one`,
      detail: `Among packages with at least one advisory on record, ${worstEcosystem.registry} averages ${worstEcosystem.perAffected} and ${bestEcosystem.registry} averages ${bestEcosystem.perAffected}.`,
      basis: `${advisories.total.toLocaleString('en')} all-time advisories across hand-picked prominent projects, from OSV. Counts are all-time, so age and scrutiny raise them as readily as danger, and the registries differ in size and age.`,
      href: '/ecosystem',
      novelty: 'Advisory counts are published per package. Nobody totals them per ecosystem.',
    });
  }

  if (questions.tags > 0 && questions.medianChange !== null && questions.medianChange < 0) {
    const holding = questions.holding[0];
    found.push({
      headline: `Stack Overflow volume fell ${Math.abs(questions.medianChange).toFixed(1)}% for the median tag in ${questions.windowDays} days`,
      detail:
        holding === undefined
          ? 'Measured across two equal windows.'
          : `Across two equal windows. That fall is now the baseline rather than the finding, so what matters is the spread around it: ${holding.tag} held up ${holding.vsMedian?.toFixed(1)} points better than the median tag.`,
      basis: `${questions.tags} tags, ${questions.total.toLocaleString('en')} questions in the recent window. A tag with under 25 questions in the earlier window gets no percentage at all.`,
      href: '/ecosystem',
      novelty: 'The collapse is discussed everywhere and measured per tag almost nowhere.',
    });
  }

  const busiest = incidents.byProvider[0];
  const quietest = [...incidents.byProvider].reverse().find((row) => row.count === 0);
  if (busiest !== undefined && busiest.count > 0) {
    found.push({
      headline: `${busiest.name} announced ${busiest.count} incidents in ${incidents.windowDays} days`,
      detail: `Their own status page, kept after it stopped carrying them.${quietest === undefined ? '' : ` ${quietest.name} announced none in the same window.`} A count measures how often a provider publishes, so one that discloses every degradation out-counts one that stays quiet.`,
      basis: `${incidents.total.toLocaleString('en')} incidents across ${incidents.providers} providers, ${incidents.observedDays} days on record here. Never read a low number as a good one.`,
      href: '/incidents',
      novelty: 'Every status page forgets after a few months. This one does not.',
    });
  }

  if (hiring.month !== null && hiring.sample > 0) {
    const top = hiring.top[0];
    const mover = hiring.rising[0] ?? hiring.falling[0];
    if (top !== undefined) {
      found.push({
        headline: `${top.term} is named in ${top.share.toFixed(1)}% of hiring posts`,
        detail: `Counted across one month of Hacker News job posts.${mover === undefined || mover.move === null ? '' : ` The largest move against last month is ${mover.term}, ${mover.move > 0 ? 'up' : 'down'} ${Math.abs(mover.move).toFixed(1)} points.`}`,
        basis: `${hiring.sample} posts in ${hiring.month}, compared against ${hiring.previousSample} the month before. One forum, skewed hard toward American startups — evidence about that population and no wider one.`,
        href: '/incidents',
        novelty: 'Every other signal here measures what developers publish. This measures what somebody paid to ask for.',
      });
    }
  }

  const heavy = images.heaviest[0];
  const light = images.stalest.find((row) => row.overLightest === null);
  if (heavy !== undefined && light !== undefined && heavy.bytes > light.bytes) {
    found.push({
      headline: `The heaviest base image tracked here is ${Math.round(heavy.bytes / light.bytes)}× the lightest`,
      detail: `${heavy.image}:${heavy.tag} is ${Math.round(heavy.bytes / 1e6)} MB against ${Math.round(light.bytes / 1e6)} MB for ${light.image}:${light.tag}, on every pull, on every build.`,
      basis: `${images.tags} tags across ${images.images} official images, read daily from Docker Hub with the date each was last rebuilt.`,
      novelty: 'Sizes are published per tag. Nobody puts them beside each other.',
      href: '/ecosystem',
    });
  }

  if (lifecycle.approaching > 0) {
    const soonest = lifecycle.soon[0];
    if (soonest !== undefined) {
      found.push({
        headline: `${lifecycle.approaching} tracked ${plural(lifecycle.approaching, 'release line stops', 'release lines stop')} getting security fixes within a year`,
        detail: `The soonest is ${soonest.product} ${soonest.cycle}, which ends on ${soonest.eol} — ${soonest.days} days away.`,
        basis: `${lifecycle.products} runtimes, databases and frameworks, read daily from endoflife.date. Dates are theirs and republished unchanged; nothing here is inferred.`,
        href: '/stack',
        novelty: 'The dates are announced years ahead and watched by almost nobody.',
      });
    }
  }

  return found;
}

export function renderFindings(index: IndexBundle, meta: MetaRecord): string {
  const findings = findingsFrom(index);

  const body =
    findings.length === 0
      ? `<p class="notice">Nothing has enough behind it to state yet. Findings appear here once the
      readings they rest on clear their own bars, and not before.</p>`
      : findings
          .map(
            (finding, position) => `<article class="finding-card">
  <div class="repo-facts">
    <span class="label">Finding ${position + 1} of ${findings.length}</span>
    <a class="label" href="${esc(finding.href)}">See the readings</a>
  </div>
  <h2 class="finding-headline">${esc(finding.headline)}</h2>
  <p class="finding-detail">${esc(finding.detail)}</p>
  <p class="finding-basis"><strong>What it rests on.</strong> ${esc(finding.basis)}</p>
  ${finding.novelty === '' ? '' : `<p class="finding-basis"><strong>Why it is not published elsewhere.</strong> ${esc(finding.novelty)}</p>`}
</article>`,
          )
          .join('');

  return layout({
    title: 'Findings — what the readings actually say',
    description:
      'The things this instrument has measured that are not published anywhere else, each stated plainly with its sample and a link to the evidence.',
    current: '/findings',
    path: '/findings',
    index,
    meta,
    body: `<section class="hero">
  <h1 class="hero-thesis">What the readings actually say.</h1>
  <p class="hero-sub">
    Every other page here is a table, which is the right shape for a reading and the wrong shape
    for a claim. These are the things worth saying out loud — each with the sample it rests on and
    a link to the numbers behind it.
  </p>
  <p class="hero-follow">
    Every sentence on this page is assembled from the published data with its figures filled in.
    None of it is written by hand or by a model, so none of it can drift from what was measured.
    A finding whose numbers fall below the bar it needs stops appearing.
  </p>
</section>

${body}

<div class="notice">
  <strong>Check any of it</strong>
  Every figure above is in a file you can open:
  <a href="/data/index.json">index.json</a>,
  <a href="/data/ecosystem.json">ecosystem.json</a>,
  <a href="/data/incidents.json">incidents.json</a> and
  <a href="/data/eol.json">eol.json</a>. The whole reading history is committed at
  <a href="https://github.com/sighttrue/sighttrue">the agent’s own repository</a>, one commit per
  run, which is the part that makes any of this checkable rather than merely stated.
</div>`,
  });
}

/** For the social card and the feed description. Kept short enough to quote. */
export function leadFinding(index: IndexBundle): string {
  const first = findingsFrom(index)[0];
  return first === undefined ? `Readings across ${index.watchlist.active} repositories.` : first.headline;
}

export const FINDINGS_URL = `${SITE_ORIGIN}/findings`;
